require cycle warning removed by extracting dbcontext to its own file
sj19330/Counter-app pull request #2
Opened 2024-07-08 15:43 UTC by sj19330

moved the db context into its own file which is then separately imported into the app.js file and the track weight/food pages, removing the requirement cycle that we discussed!!

everything is looking good on my end, should be good to merge with no problems, not much has been changed

2024-07-08 21:44 UTC, jxz12 commented on App.js
You should also factor out the `DBContext.Provider` tag into a separate component, and then you can put the `initialiseDatabase` function into that file too.

Here is an article with an example: https://javascript.works-hub.com/learn/building-with-react-context-provider-pattern-1af4b

2024-07-08 21:45 UTC, jxz12 requested changes
please factor out the provider as well as the context into a separate file, then the database initialisation will be nicely abstracted away into its own component

2024-07-12 14:30 UTC, sj19330 reviewed
Refactored so the provideor, loading and database initialization is all in the DbContext.js file instead of the App.js. Tested database with the log weight and log food pages and all is working well : )

2024-07-12 19:05 UTC, jxz12 commented on DbContext.js
> +export default function DataBaseContext({ children }) {
This should be named `Provider` instead of Context, so `DBProvider` would be better.

2024-07-12 19:05 UTC, jxz12 approved these changes
good work, feel free to merge after renaming the provider class!

2024-07-18 10:04 UTC, merged